# -*- coding: utf-8 -*-
{
    "name": "RH Costa Rica - Nómina Odoo 18",
    "summary": "Localización nativa y parametrizable de nómina de Costa Rica para Odoo 18 Enterprise",
    "version": "18.0.11.0.0",
    "category": "Human Resources/Payroll",
    "author": "Castro Li",
    "website": "https://castrolicr.com",
    "license": "LGPL-3",
    "depends": [
        "hr_payroll",
        "hr_payroll_account",
        "hr_contract",
        "hr_holidays",
        "hr_attendance",
        "account",
    ],
    "data": [
        "security/ir.model.access.csv",
        "data/payroll_categories.xml",
        "data/work_entry_types.xml",
        "data/input_types.xml",
        "data/leave_types.xml",
        "data/legal_parameters_2026.xml",
        "data/disability_rules.xml",
        "data/payroll_structures.xml",
        "data/salary_rules.xml",
        "data/social_salary_rules.xml",
        "views/legal_parameter_views.xml",
        "views/social_contribution_views.xml",
        "views/tax_bracket_views.xml",
        "views/deduction_views.xml",
        "views/payroll_incident_views.xml",
        "views/disability_rule_views.xml",
        "views/severance_views.xml",
        "views/hr_employee_views.xml",
        "views/hr_contract_views.xml",
        "views/hr_payslip_run_views.xml",
        "views/res_config_settings_views.xml",
        "views/menu_views.xml",
        "wizard/generate_holidays_views.xml",
        "data/native_setup.xml",
    ],
    "installable": True,
    "application": True,
    "auto_install": False,
}
