from . import legal_parameter
from . import social_contribution
from . import tax_bracket
from . import public_holiday
from . import payroll_deduction
from . import hr_employee
from . import hr_contract
from . import res_company
from . import hr_payslip
from . import payroll_incident
from . import disability_rule
from . import severance
